# Generated by Django 5.2.3 on 2025-06-10 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_image_project_tags_alter_project_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='full_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='screenshots',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='video',
            field=models.URLField(blank=True),
        ),
    ]
