# Generated by Django 5.2.3 on 2025-06-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_profilepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshot',
            name='description',
            field=models.TextField(default='hu'),
            preserve_default=False,
        ),
    ]
